# configs/exp1.yaml

experiment_name: "exp1_simplegcn"

# Data parameters
data_path: "data/raw_data.csv"
label_col: "price"
train_val_test_split: [0.7, 0.15, 0.15]

# Graph parameters
graph_type: "spatial"
radius1_k: 30
radius2_k: 20
radius3_k: 0
top_k_sim: 7
geo_features: ["lat", "long"]

# Model parameters
GNN_model_type: "SimpleGCN"
GNN_model_params:
  input_dim: 18   # מספר הפיצ'רים אחרי feature engineering
  hidden_dim: 128
  dropout: 0.4

# Training parameters
optimizer: "Adam"
criterion: "MSELoss"
learning_rate: 0.001
epochs: 20
batch_size: 32

# Evaluation/Output
save_experiment_path: "experiments/"
what_to_visualize:
  - "training_loss"
  - "validation_metrics"
