experiment_name: "exp4_tiny_test"

# Data parameters
data_path: "data/raw_data.csv"
label_col: "price"
train_val_test_split: [0.05, 0.05, 0.9]

# Graph parameters
graph_type: "spatial"
radius1_k: 2
radius2_k: 0
radius3_k: 0
top_k_sim: 1
geo_features: ["lat", "long"]

# Model parameters
GNN_model_type: "SimpleGCN"
GNN_model_params:
  input_dim: 18
  hidden_dim: 16
  dropout: 0.1

# Training parameters
optimizer: "Adam"
criterion: "MSELoss"
learning_rate: 0.001
epochs: 3
batch_size: 8

# Evaluation/Output
save_experiment_path: "experiments/"
what_to_visualize:
  - "training_loss"
  - "validation_metrics"
  - "graph_structure"
