experiment_name: "exp5_simplegat"

# Data parameters
data_path: "data/raw_data.csv"
label_col: "price"
train_val_test_split: [0.6, 0.2, 0.2]  

# Graph parameters
graph_type: "spatial"
radius1_k: 20          
radius2_k: 15
radius3_k: 0
top_k_sim: 5
geo_features: ["lat", "long"]

# Model parameters
GNN_model_type: "SimpleGAT"
GNN_model_params:
  input_dim: 18
  hidden_dim: 64             
  dropout: 0.3

# Training parameters
optimizer: "Adam"
criterion: "MSELoss"
learning_rate: 0.0005         
epochs: 10                    
batch_size: 16                

# Evaluation/Output
save_experiment_path: "experiments/"
what_to_visualize:
  - "training_loss"
  - "validation_metrics"
