experiment_name: "exp_multilayergcn"

# Data parameters
data_path: "data/raw_data.csv"
label_col: "price"
train_val_test_split: [0.7, 0.15, 0.15]

# Graph parameters
graph_type: "spatial"
radius1_k: 30
radius2_k: 20
radius3_k: 5
top_k_sim: 7
geo_features: ["lat", "long"]

# Model parameters
GNN_model_type: "MultiLayerGCN"
GNN_model_params:
  input_dim: 18
  hidden_dims: [256, 128, 64, 32, 16]
  dropout: 0.4

# Training parameters
optimizer: "Adam"
criterion: "MSELoss"
learning_rate: 0.001
epochs: 20
batch_size: 32

# Output
save_experiment_path: "experiments/"
what_to_visualize:
  - "training_loss"
  - "validation_metrics"
